### ISSUE TITLE
bug: invalid literal for int() with base 16: '0.684'

### ISSUE THREAD

**Issue by perryascott** [RubiconDeFi/rubi-py#43]
I'm having an issue with the client.add_pair() function. Here is what the code looks like so far, borrowed entirely from the quickstart guide.

```
import os
from dotenv import load_dotenv
from decimal import Decimal

from rubi import Client

# load from env file
load_dotenv(".env")

# set the env variables
http_node_url = os.getenv("HTTP_NODE_URL")
wallet = os.getenv("WALLET")
key = os.getenv("KEY")

# instantiate the client
client = Client.from_http_node_url(
    http_node_url=http_node_url,
    wallet=wallet,
    key=key
)

# add the WETH/USDC pair to the client
# the base asset is WETH and the quote asset is USDC
client.add_pair(
    pair_name="WETH/USDC",
    base_asset_allowance=Decimal("1"),
    quote_asset_allowance=Decimal("10000")
)
```

and the resulting error:

```
Traceback (most recent call last):
  File "/Users/perryscott/Desktop/rubicon/./rubi_test.py", line 25, in <module>
    client.add_pair(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 159, in add_pair
    self.update_pair_allowance(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 194, in update_pair_allowance
    self._update_asset_allowance(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 603, in _update_asset_allowance
    asset.approve(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/erc20.py", line 203, in approve
    return self._default_transaction_handler(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/base_contract.py", line 222, in _default_transaction_handler
    return self._wait_for_transaction_receipt(transaction=signed_txn)
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/base_contract.py", line 267, in _wait_for_transaction_receipt
    result = TransactionReceipt.from_tx_receipt(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/contract_types/transaction_reciept.py", line 56, in from_tx_receipt
    l1_fee_scalar=None if tx_receipt.get("l1FeeScalar") is None else int(tx_receipt.get("l1FeeScalar"), 16)
ValueError: invalid literal for int() with base 16: '0.684'
```

I've also tried removing the quotations in the Decimal() function as well as other pair combinations and values. Let me know if there's something I'm missing. Thanks.

Also a heads up, in the docs quickstart section the 'from decimal import Decimal' import is missing and an extra 'client = ' found it's way into the Client() declaration.

**Comment by perryascott** [comment]
Also seeing the same problem when using the examples.

**Comment by denverbaumgartner** [comment]
thank you @perryascott for reporting this bug. this has been resolved in this pr: https://github.com/RubiconDeFi/rubi-py/pull/48 and has been updated to [pypi](https://pypi.org/project/rubi/) in release `2.0.5`

please let us know if you encounter any other problems and we will be happy to resolve them ASAP. additionally, if you have any feature requests do let us know!
