### ISSUE TITLE
bug: Insufficient Funds

### ISSUE THREAD

**Issue by perryascott** [RubiconDeFi/rubi-py#51]
Experiencing an issue with "insufficient funds". It looks like the numbers I'm inputting in the add_pair() allowance are larger than the minimum fee values outlined here: https://docs.rubicon.finance/protocol/rubicon-market/min-order-sizes

I have at least 50% of each of the values that I am using in the add pair functions.

```
import logging as log
import os
from _decimal import Decimal
from multiprocessing import Queue

from dotenv import load_dotenv

from rubi import Client

# load from env file
load_dotenv(".env")

# set logging config
log.basicConfig(level=log.INFO)

# set the env variables
http_node_url = os.getenv("HTTP_NODE_URL")
wallet = os.getenv("WALLET")
key = os.getenv("KEY")

queue = Queue()

# create client
client = Client.from_http_node_url(
    http_node_url=http_node_url,
    # custom_token_addresses_file="custom_token_addresses.yaml",
    wallet=wallet,
    key=key,
    message_queue=queue
)

client.add_pair(
    pair_name="WETH/USDC",
    base_asset_allowance=Decimal(.005),
    quote_asset_allowance=Decimal(100)
)
```

and here is the traceback that I get:

```

Traceback (most recent call last):
  File "/Users/perryscott/Desktop/rubicon/./rubi_test2.py", line 32, in <module>
    client.add_pair(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 159, in add_pair
    self.update_pair_allowance(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 194, in update_pair_allowance
    self._update_asset_allowance(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/client.py", line 603, in _update_asset_allowance
    asset.approve(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/erc20.py", line 203, in approve
    return self._default_transaction_handler(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/rubi/contracts/base_contract.py", line 220, in _default_transaction_handler
    self.w3.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/web3/eth/eth.py", line 372, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "/Users/perryscott/Desktop/rubicon/rubi_env/lib/python3.10/site-packages/web3/manager.py", line 205, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

**Comment by perryascott** [comment]
Resolved:

This was actually just due to insufficient funds.
