### ISSUE TITLE
Bug: ValueError: 42161 is not a valid NetworkId

### ISSUE THREAD

**Issue by perryascott** [RubiconDeFi/rubi-py#75]
Hey guys,

I'm trying to create a Arbitrum client using the following function:
```
    client = Client.from_http_node_url(
        http_node_url=os.getenv("HTTP_NODE_URL"),
        wallet= os.getenv("WALLET"),
        key=os.getenv("KEY"),
        message_queue=queue
    )
```

I've tried several arbitrum endpoints such as :
- Alchemy.com
- Blastpi.io
- quicknode.com

All of the node url's I've gotten from these websites yield the same errors:

```
https://indulgent-old-borough.arbitrum-mainnet.discover.quiknode.pro/perry's_api_key/
Traceback (most recent call last):
  File "/home/ec2-user/rubi-volume-bot/./app.py", line 114, in <module>
    client = get_client(queue=my_queue, pair=token)
  File "/home/ec2-user/rubi-volume-bot/utils.py", line 73, in get_client
    client = Client.from_http_node_url(
  File "/home/ec2-user/.local/lib/python3.10/site-packages/rubi/client.py", line 105, in from_http_node_url
    network = Network.from_config(
  File "/home/ec2-user/.local/lib/python3.10/site-packages/rubi/network/network.py", line 125, in from_config
    network_name = NetworkId(w3.eth.chain_id).name.lower()
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 42161 is not a valid NetworkId
```

Is there a preferred provider I should be using to do this?

**Comment by adamamsmith** [comment]
@perryascott we have opened a PR to resolve this: https://github.com/RubiconDeFi/rubi-py/pull/74

Will update as soon as this is merged in 👍

**Comment by adamamsmith** [comment]
@perryascott this fix has been merged in 👍
